set -g @color_bg "#171B20"
set -g @color_fg "#E7EAEE"
set -g @color_text "#171B20"
set -g @color_comment "#586172"
set -g @color_date "#5CCEFF"
set -g @color_time "#FFE77A"
set -g @color_alert "#F97791"
set -g @color_pomodoro "#F73F64"
set -g @color_session "#38FFA5"
set -g @color_window "#545c7e"
